spring:
  application:
    name: eureka-client
server:
  port: 10001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@cn.com.jl.spring.cloud:10000/eureka/